### ISSUE TITLE
This experimental syntax requires enabling the parser plugin: 'exportDefaultFrom'

### ISSUE THREAD

**Issue by plemarquand** [s-yadav/relative-to-alias#4]
Affected Version: `2.0.0`

A fresh install now throws the error below. `v1.1.0` doesn't have the issue.

```
SyntaxError: This experimental syntax requires enabling the parser plugin: 'exportDefaultFrom' (1:7)
    at Object.raise (/Users/plemarquand/.nvm/versions/node/v12.4.0/lib/node_modules/relative-to-alias/node_modules/@babel/parser/lib/index.js:6400:17)
    at Object.expectPlugin (/Users/plemarquand/.nvm/versions/node/v12.4.0/lib/node_modules/relative-to-alias/node_modules/@babel/parser/lib/index.js:7733:18)
    at Object.maybeParseExportDefaultSpecifier (/Users/plemarquand/.nvm/versions/node/v12.4.0/lib/node_modules/relative-to-alias/node_modules/@babel/parser/lib/index.js:11022:12)
    at Object.parseExport (/Users/plemarquand/.nvm/versions/node/v12.4.0/lib/node_modules/relative-to-alias/node_modules/@babel/parser/lib/index.js:10974:29)
    at Object.parseExport (/Users/plemarquand/.nvm/versions/node/v12.4.0/lib/node_modules/relative-to-alias/node_modules/@babel/parser/lib/index.js:2232:24)
    at Object.parseStatementContent (/Users/plemarquand/.nvm/versions/node/v12.4.0/lib/node_modules/relative-to-alias/node_modules/@babel/parser/lib/index.js:10036:27)
    at Object.parseStatement (/Users/plemarquand/.nvm/versions/node/v12.4.0/lib/node_modules/relative-to-alias/node_modules/@babel/parser/lib/index.js:9932:17)
    at Object.parseStatement (/Users/plemarquand/.nvm/versions/node/v12.4.0/lib/node_modules/relative-to-alias/node_modules/@babel/parser/lib/index.js:2025:26)
    at Object.parseBlockOrModuleBlockBody (/Users/plemarquand/.nvm/versions/node/v12.4.0/lib/node_modules/relative-to-alias/node_modules/@babel/parser/lib/index.js:10508:25)
    at Object.parseBlockBody (/Users/plemarquand/.nvm/versions/node/v12.4.0/lib/node_modules/relative-to-alias/node_modules/@babel/parser/lib/index.js:10495:10) {
  pos: 7,
  loc: Position { line: 1, column: 7 },
  missingPlugin: [ 'exportDefaultFrom' ]
```

**Comment by s-yadav** [comment]
Pushed a fix. Let me know if it works.

**Comment by plemarquand** [comment]
Resolved! Thanks for the quick turnaround.
