### ISSUE TITLE
Cannot run on node due to syntax error

### ISSUE THREAD

**Issue by HonzaMac** [s-yadav/relative-to-alias#6]
I've followed installation on my node v10. 

When I run this command: `relative-to-alias --root backend/ --src . --alias _aws --alias-path server/aws`

I keep getting this error:
```
/Users/honzamac/project/smart/ecosystem/backend/node_modules/@babel/parser/lib/index.js:6946
      throw err;
      ^

SyntaxError: Binding 'arguments' in strict mode (7:27)
    at Object.raise (/Users/honzamac/project/smart/ecosystem/backend/node_modules/@babel/parser/lib/index.js:6930:17)
    at Object.checkLVal (/Users/honzamac/project/smart/ecosystem/backend/node_modules/@babel/parser/lib/index.js:8745:16)
    at Object.checkLVal (/Users/honzamac/project/smart/ecosystem/backend/node_modules/@babel/parser/lib/index.js:2417:20)
    at Object.checkParams (/Users/honzamac/project/smart/ecosystem/backend/node_modules/@babel/parser/lib/index.js:10202:12)
    at Object.checkParams (/Users/honzamac/project/smart/ecosystem/backend/node_modules/@babel/parser/lib/index.js:2780:18)
    at Object.parseFunctionBody (/Users/honzamac/project/smart/ecosystem/backend/node_modules/@babel/parser/lib/index.js:10160:12)
    at forwardNoArrowParamsConversionAt (/Users/honzamac/project/smart/ecosystem/backend/node_modules/@babel/parser/lib/index.js:2019:70)
    at Object.forwardNoArrowParamsConversionAt (/Users/honzamac/project/smart/ecosystem/backend/node_modules/@babel/parser/lib/index.js:2220:16)
    at Object.parseFunctionBody (/Users/honzamac/project/smart/ecosystem/backend/node_modules/@babel/parser/lib/index.js:2019:19)
    at Object.parseArrowExpression (/Users/honzamac/project/smart/ecosystem/backend/node_modules/@babel/parser/lib/index.js:10118:10)
```

I've tried different node versions: 6, 8, 10 - nothing worked. 

Any idea how to fix this issue?

**Comment by HonzaMac** [comment]
I don't need it anymore.
